SELECT 'PREFUCTURE',COUNT(*) FROM PREFUCTURE
UNION ALL
SELECT 'LINE',COUNT(*) FROM LINE
UNION ALL
SELECT 'STATION',COUNT(*) FROM STATION
UNION ALL
SELECT 'GROUP',COUNT(*) FROM TGROUP
UNION ALL
SELECT 'STATION_JOIN',COUNT(*) FROM STATION_JOIN;

Class clazz = Class.forName(className);
Service service = (Service)clazz.newInstance();