CREATE TABLE IF NOT EXISTS `PREFUCTURE` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT '路線情報JSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT '都道府県路線情報';

CREATE TABLE IF NOT EXISTS `LINE` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT '路線情報JSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT '路線情報';

CREATE TABLE IF NOT EXISTS `STATION` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT '駅情報JSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT '駅情報';

CREATE TABLE IF NOT EXISTS `TGROUP` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT 'グループJSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT 'グループ情報';

CREATE TABLE IF NOT EXISTS `STATION_JOIN` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT 'グループJSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT '隣接駅情報';