CREATE TABLE IF NOT EXISTS `PREFUCTURE` (
  `ID` INT(2) NOT NULL COMMENT 'ID',
  `JSON` MEDIUMTEXT NOT NULL COMMENT '路線情報JSON',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT '都道府県路線情報';